### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by freeman29** [webpack-contrib/script-loader#19] opened 2016-11-04 08:04 UTC
Hi guys,

How can I fix this issue?

Thanks!

**Comment by adamasantares** [comment] 2017-03-26 09:11
I got same error but with Twitter's typeahead.js :(

```js
import Bloodhound from 'script-loader!./typeahead/bloodhound.min.js';
import Typeahead from 'script-loader!./typeahead/typeahead.jquery.min.js';
```

```
module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
		eval.call(null, src);    // <== Uncaught TypeError: Cannot set property 'Bloodhound' of undefined
}
```

**Comment by michael-ciniawsky** [comment] 2017-03-26 14:07
maybe related to #13

**Comment by michael-ciniawsky** [comment] 2017-03-26 14:09
@adamasantares Form a first glance I think this is the cause too, if you havea workaround && time mind sending a quick PR 😛 ?

**Comment by adamasantares** [comment] 2017-03-27 04:58
@michael-ciniawsky 

Hey, I found solution, check there https://github.com/twitter/typeahead.js/issues/1627

**Comment by michael-ciniawsky** [comment] 2017-03-27 15:52
@adamasantares Thx very much I see 😛, closing since this is solve by using `imports-loader` instead for 'incompatible'  files

**Closed by michael-ciniawsky** 2017-03-27 15:52 UTC
Labels: bug, question
